name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  sqleto:
    path: ../sqleto/

dev_dependencies:
  sqleto_generator:
    path: ../sqleto_generator/

  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
