name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  sqleto:
    path: ../sqleto/

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3
  sqleto_generator: ^0.0.3+2
