targets:
  $default:
    builders:
      sqleto_generator:schemaBuilder:
        options:
          build_to:
            - lib/*

builders:
  schemaBuilder:
    import: "package:sqleto_generator/sqleto_generator.dart"
    builder_factories: ["schemaBuilder"]
    build_extensions: { ".dart": [".g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
