name: sqleto_generator
description: Code generator for use with package SQLeto
version: 0.0.3+1
homepage: https://tihrasguinho.dev
repository: https://github.com/tihrasguinho/sqleto.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  sqleto_annotation: ^0.0.4+3
  source_gen: ">=1.0.0 <2.0.0"
  build: ">=2.0.0 <3.0.0"
  analyzer: ">=5.0.0 <6.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
