name: sqleto
description: A ORM-ish for use with PostgreSQL
version: 0.0.5+6
homepage: https://tihrasguinho.dev
repository: https://github.com/tihrasguinho/sqleto.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  sqleto_annotation: ^0.0.4+3
  postgres: ">=2.0.0 <3.0.0"
  rxdart: ">=0.27.0 <1.0.0"
  crypto: ">=3.0.2 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  faker: ^2.1.0
