name: sqleto
description: A ORM-ish for ush with PostgreSQL
version: 0.0.1
homepage: https://tihrasguinho.dev
repository: https://github.com/tihrasguinho/sqleto.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  sqleto_annotation: ^0.0.1
  postgres: ">=2.0.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
