name: sqleto
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.4 <3.0.0"

dependencies:
  sqleto_annotation:
    git:
      url: https://github.com/tihrasguinho/sqleto.git
      path: sqleto_annotation
      ref: master

  postgres: ">=2.0.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.3.3

  sqleto_generator:
    git:
      url: https://github.com/tihrasguinho/sqleto.git
      path: sqleto_generator
      ref: master
