name: Publish SQLeto to pub.dev

on:
  push:
    tags:
      - "sqleto-[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
      - name: Go to correct directory
        run: cd sqleto
      - name: Publish
        run: dart pub publish --force
